const CONSTANTS = {
    COLOR_PRIMARY: 0x4e342e,
    COLOR_LIGHT: 0x7b5e57,
    COLOR_DARK: 0x260e04,
    COLOR_STROKE: 0xdddddd,
    COLOR_DONE: 0x50c878,
    COLOR_START_OPTIONS: 0xffffff,
    COLOR_START_OPTIONS_BG: 0x000000,
    DEFAULT_VOLUME_VALUE: 0.4,

    SCENES: {
        MAIN_SCENE: "MAIN_SCENE",
        START_VIEW_SCENE: "START_VIEW_SCENE",
        MAP_VIEW_SCENE: "MAP_VIEW_SCENE",
        OPTIONS_VIEW_SCENE: "OPTIONS_VIEW_SCENE",
        CONTROLS_VIEW_SCENE: "CONTROLS_VIEW_SCENE"
    }
};
export default CONSTANTS;